// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Notifier is an autogenerated mock type for the Notifier type
type Notifier struct {
	mock.Mock
}

// NotifyOnRegister provides a mock function with given fields: recipient
func (_m *Notifier) NotifyOnRegister(recipient string) (string, error) {
	ret := _m.Called(recipient)

	var r0 string
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(recipient)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(recipient)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
